### ISSUE TITLE
Unable to start activity ComponentInfo{com.unify.luluandsky/com.payu.ui.view.activities.CheckoutActivity}: android.view.InflateException: Binary XML file line #63 in com.unify.luluandsky:layout/activity_checkout_collapsing: Could not inflate Behavior subclass android.support.design.widget.AppBarLayout$ScrollingViewBehavior

### ISSUE THREAD

**Issue by sushantchaturvedi1895** [payu-intrepos/PayUCheckoutPro-Android#3]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.unify.luluandsky/com.payu.ui.view.activities.CheckoutActivity}: android.view.InflateException: Binary XML file line #63 in com.unify.luluandsky:layout/activity_checkout_collapsing: Could not inflate Behavior subclass android.support.design.widget.AppBarLayout$ScrollingViewBehavior
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.view.InflateException: Binary XML file line #63 in com.unify.luluandsky:layout/activity_checkout_collapsing: Could not inflate Behavior subclass android.support.design.widget.AppBarLayout$ScrollingViewBehavior
     Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass android.support.design.widget.AppBarLayout$ScrollingViewBehavior
        at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:649)
        at androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2896)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1740)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:112)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1129)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.payu.ui.view.activities.CheckoutActivity.onCreate(SourceFile:9)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: android.support.design.widget.AppBarLayout$ScrollingViewBehavior
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)

**Comment by Rahul-Hooda** [comment]
@sushantchaturvedi1895 - Please confirm if the issue is resolved. If not, kindly drop a mail to mobile.integration@payu.in

**Comment by Rahul-Hooda** [comment]
Closing due to no inactivity..

**Comment by rajdeep74** [comment]
I am also facing exact same issue today , Can you please help me how to solve this ?
