### ISSUE TITLE
Unknown animation name: animator

### ISSUE THREAD

**Issue by rajaryan9358** [payu-intrepos/PayUCheckoutPro-Android#43]
Getting some animation related issue in payu checkout pro, someone, show to fix it?

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.genericchatapp, PID: 9802
    java.lang.RuntimeException: Unknown animation name: animator
        at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:198)
        at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:182)
        at android.view.animation.AnimationUtils.createAnimationFromXml(AnimationUtils.java:158)
        at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:139)
        at com.payu.ui.view.activities.CheckoutActivity.onPrepareOptionsMenu(SourceFile:7)
        at android.app.Activity.onPreparePanel(Activity.java:4509)
        at androidx.activity.ComponentActivity.onPreparePanel(ComponentActivity.java:512)
        at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:100)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3477)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8152)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by rajaryan9358** [comment]
Sorry,

it was not related to payu.
